services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fleet_management
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: fleet_management
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "50051:50051"  # Adicionado para expor a porta gRPC
    volumes:
      - .:/app
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "./main"]

volumes:
  db-data:
